spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.17.0.2/sitm_409
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9090
tkn:
  api:
    url: 172.17.1.20:8090/api
    fail-fast: false
    hierarchy: false
  reply:
    rate: 3000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
---
spring:
  profiles: via
tkn:
  reply:
    rate: 30000
server:
  port: 9090

---
spring:
  profiles: cde
server:
  port: 8090

---
spring:
  profiles: oviedo
tkn:
  api:
    url: localhost:8090/api
    
---

spring:
  profiles: cde
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.17.0.2/ACA_SITM
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8090
